name: USB_Share
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+7

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.3
  lottie:
  unicons:
  dio: ^4.0.6
  path_provider: ^2.0.11
  get_it: ^7.2.0
  get:
  path: ^1.8.1
  animated_splash_screen:
  flex_color_scheme:
  url_launcher: ^6.1.5
  page_transition:
  shared_preferences: ^2.0.15
  introduction_screen: ^3.0.2
  mailto: ^2.0.0
  receive_sharing_intent: ^1.4.5
  modal_bottom_sheet:
  flutter_displaymode: ^0.4.1
  adaptive_theme:
  system_settings:
  stop_watch_timer:
  flutter_markdown:
  device_apps:
  http:
  provider:
  file_picker:
  hive:
  permission_handler: ^10.0.1
  qr_flutter: ^4.0.0
  qrscan:
  widgets_to_image:
  screenshot: ^1.3.0
  share_plus: ^6.3.0
  image_gallery_saver: ^1.7.1
  hive_flutter: ^1.1.0
  flutter_file_manager:
  image_picker: ^0.8.7+5
  flutter_image_compress: ^1.1.3
  image_cropper: ^3.0.1
  photo_view: ^0.14.0
  tab_indicator_styler: ^2.0.0
  intl: ^0.18.0
  easy_folder_picker: ^1.3.0
  flutter_local_notifications: ^13.0.0
  flutter_spinkit: ^5.1.0
  csv: ^5.0.1
  rxdart: ^0.27.7
  flutter_launcher_icons:
  win32:
  open_file_plus: ^3.3.0
  webview_windows: ^0.2.2
  webview_flutter: ^4.0.7
  image_size_getter: ^2.1.2
  # aspose_words_cloud: ^23.2.0
  html: ^0.15.2
  xml: ^6.2.2
  docx_template: ^0.3.4
  cherry_toast: ^1.2.1
  loading_animation_widget: ^1.2.0+4
  image_cropping: ^0.0.13
  image_compression_flutter: ^1.0.0
  device_info_plus:
  easy_stepper:
  just_the_tooltip: ^0.0.12
  cool_alert: ^2.0.1

  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding
      path: plugins/window_size

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_distributor:
  msix: ^2.8.18

msix_config:
  display_name: Photon
  publisher_display_name: N/A
  identity_name: dev.abhi.photon
  msix_version: 1.1.1.0
  logo_path: assets\images\icon.png
  capabilities: internetClient, internetServer
  certificate_path: thekeystore.pfx
  certificate_password:
  archive:

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/lottie/
    - assets/images/
    - assets/texts/
    - assets/avatars/
    - assets/data/
    - assets/docs/ckeditor5/import-word.html
    - assets/importWord.py
    - assets/exportWord.py
    - assets/kendo/
    - assets/kendo/kendoEditor.html
    - assets/kendo/default-main.css
    - assets/kendo/jquery.js
    - assets/kendo/kendo.all.js

flutter_icons:
  image_path: "assets/images/cardio_icon.png"
  android: true
  ios: true
# fonts:
#     - family: ytf
#       fonts:
#         - asset: assets/fonts/Yftoow-R.ttf
#     - family: questrial
#       fonts:
#         - asset: assets/fonts/Questrial-Regular.ttf
